///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoSite_01
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AccountRegistration recording.
    /// </summary>
    [TestModule("585c511d-e758-45ac-819b-149206721e02", ModuleType.Recording, 1)]
    public partial class AccountRegistration : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoSite_01Repository repository.
        /// </summary>
        public static DemoSite_01Repository repo = DemoSite_01Repository.Instance;

        static AccountRegistration instance = new AccountRegistration();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AccountRegistration()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AccountRegistration Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test' with focus on 'MagentoTesting.AccountRegistration.Firstname'.", repo.MagentoTesting.AccountRegistration.FirstnameInfo, new RecordItemIndex(0));
            repo.MagentoTesting.AccountRegistration.Firstname.PressKeys("Test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Account6' with focus on 'MagentoTesting.AccountRegistration.Lastname'.", repo.MagentoTesting.AccountRegistration.LastnameInfo, new RecordItemIndex(1));
            repo.MagentoTesting.AccountRegistration.Lastname.PressKeys("Account6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test.account6{LShiftKey down}@{LShiftKey up}gmail.com' with focus on 'MagentoTesting.AccountRegistration.EmailAddress'.", repo.MagentoTesting.AccountRegistration.EmailAddressInfo, new RecordItemIndex(2));
            repo.MagentoTesting.AccountRegistration.EmailAddress.PressKeys("test.account6{LShiftKey down}@{LShiftKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test1234' with focus on 'MagentoTesting.AccountRegistration.Password'.", repo.MagentoTesting.AccountRegistration.PasswordInfo, new RecordItemIndex(3));
            repo.MagentoTesting.AccountRegistration.Password.PressKeys("Test1234");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test1234' with focus on 'MagentoTesting.AccountRegistration.PasswordConfirmation'.", repo.MagentoTesting.AccountRegistration.PasswordConfirmationInfo, new RecordItemIndex(4));
            repo.MagentoTesting.AccountRegistration.PasswordConfirmation.PressKeys("Test1234");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.AccountRegistration.CreateAnAccount1' at 119;6.", repo.MagentoTesting.AccountRegistration.CreateAnAccount1Info, new RecordItemIndex(5));
            repo.MagentoTesting.AccountRegistration.CreateAnAccount1.Click("119;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Thank you for registering with Main Website Store.') on item 'MagentoTesting.AccountRegistration.ThankYouForRegisteringWithMainWebs'.", repo.MagentoTesting.AccountRegistration.ThankYouForRegisteringWithMainWebsInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.MagentoTesting.AccountRegistration.ThankYouForRegisteringWithMainWebsInfo, "InnerText", "Thank you for registering with Main Website Store.");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
