///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoSite_01
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddingOneItemInCart recording.
    /// </summary>
    [TestModule("ebf87a4f-5a5a-415e-9087-4215cfc56e21", ModuleType.Recording, 1)]
    public partial class AddingOneItemInCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoSite_01Repository repository.
        /// </summary>
        public static DemoSite_01Repository repo = DemoSite_01Repository.Instance;

        static AddingOneItemInCart instance = new AddingOneItemInCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddingOneItemInCart()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddingOneItemInCart Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.UiCornerAllUiMenuUiWidgetUiWidge.Women' at Center.", repo.MagentoTesting.UiCornerAllUiMenuUiWidgetUiWidge.WomenInfo, new RecordItemIndex(0));
            repo.MagentoTesting.UiCornerAllUiMenuUiWidgetUiWidge.Women.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.Maincontent.HoodiesSweatshirts' at Center.", repo.MagentoTesting.Maincontent.HoodiesSweatshirtsInfo, new RecordItemIndex(1));
            repo.MagentoTesting.Maincontent.HoodiesSweatshirts.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\nCirce Hooded Ice Fleece ') on item 'MagentoTesting.Maincontent.ATagCirceHoodedIceFleece'.", repo.MagentoTesting.Maincontent.ATagCirceHoodedIceFleeceInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.MagentoTesting.Maincontent.ATagCirceHoodedIceFleeceInfo, "InnerText", "\nCirce Hooded Ice Fleece ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.Maincontent.ColorSwatchOption' at Center.", repo.MagentoTesting.Maincontent.ColorSwatchOptionInfo, new RecordItemIndex(3));
            repo.MagentoTesting.Maincontent.ColorSwatchOption.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.Maincontent.DivTagM' at 27;19.", repo.MagentoTesting.Maincontent.DivTagMInfo, new RecordItemIndex(4));
            repo.MagentoTesting.Maincontent.DivTagM.Click("27;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.Maincontent.AddToCart' at 45;-1.", repo.MagentoTesting.Maincontent.AddToCartInfo, new RecordItemIndex(5));
            repo.MagentoTesting.Maincontent.AddToCart.Click("45;-1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(6));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
