///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DemoSite_01
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DemoSite_01Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("8da48f1f-e6e6-475b-bb3a-0a59fc9ea6b8")]
    public partial class DemoSite_01Repository : RepoGenBaseFolder
    {
        static DemoSite_01Repository instance = new DemoSite_01Repository();
        DemoSite_01RepositoryFolders.MagentoTestingAppFolder _magentotesting;

        /// <summary>
        /// Gets the singleton class instance representing the DemoSite_01Repository element repository.
        /// </summary>
        [RepositoryFolder("8da48f1f-e6e6-475b-bb3a-0a59fc9ea6b8")]
        public static DemoSite_01Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DemoSite_01Repository() 
            : base("DemoSite_01Repository", "/", null, 0, false, "8da48f1f-e6e6-475b-bb3a-0a59fc9ea6b8", ".\\RepositoryImages\\DemoSite_01Repository8da48f1f.rximgres")
        {
            _magentotesting = new DemoSite_01RepositoryFolders.MagentoTestingAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8da48f1f-e6e6-475b-bb3a-0a59fc9ea6b8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MagentoTesting folder.
        /// </summary>
        [RepositoryFolder("c7ef2a44-1e29-48dc-9729-4b69cc73a74c")]
        public virtual DemoSite_01RepositoryFolders.MagentoTestingAppFolder MagentoTesting
        {
            get { return _magentotesting; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DemoSite_01RepositoryFolders
    {
        /// <summary>
        /// The MagentoTestingAppFolder folder.
        /// </summary>
        [RepositoryFolder("c7ef2a44-1e29-48dc-9729-4b69cc73a74c")]
        public partial class MagentoTestingAppFolder : RepoGenBaseFolder
        {
            DemoSite_01RepositoryFolders.AccountRegistrationFolder _accountregistration;
            DemoSite_01RepositoryFolders.HeaderLinksFolder _headerlinks;
            DemoSite_01RepositoryFolders.SignInFormFolder _signinform;
            DemoSite_01RepositoryFolders.HeaderCartFolder _headercart;
            DemoSite_01RepositoryFolders.MaincontentFolder _maincontent;
            DemoSite_01RepositoryFolders.UiCornerAllUiMenuUiWidgetUiWidgeFolder _uicorneralluimenuuiwidgetuiwidge;
            DemoSite_01RepositoryFolders.MinicartItemsFolder _minicartitems;
            DemoSite_01RepositoryFolders.WishlistViewFormFolder _wishlistviewform;
            RepoItemInfo _kounique1Info;
            RepoItemInfo _actionbuttoncontinueprimaryInfo;
            RepoItemInfo _placeorderInfo;
            RepoItemInfo _searchInfo;
            RepoItemInfo _search1Info;
            RepoItemInfo _saleInfo;

            /// <summary>
            /// Creates a new MagentoTesting  folder.
            /// </summary>
            public MagentoTestingAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MagentoTesting", "/dom[@domain='magento.softwaretestingboard.com']", parentFolder, 30000, null, false, "c7ef2a44-1e29-48dc-9729-4b69cc73a74c", "")
            {
                _accountregistration = new DemoSite_01RepositoryFolders.AccountRegistrationFolder(this);
                _headerlinks = new DemoSite_01RepositoryFolders.HeaderLinksFolder(this);
                _signinform = new DemoSite_01RepositoryFolders.SignInFormFolder(this);
                _headercart = new DemoSite_01RepositoryFolders.HeaderCartFolder(this);
                _maincontent = new DemoSite_01RepositoryFolders.MaincontentFolder(this);
                _uicorneralluimenuuiwidgetuiwidge = new DemoSite_01RepositoryFolders.UiCornerAllUiMenuUiWidgetUiWidgeFolder(this);
                _minicartitems = new DemoSite_01RepositoryFolders.MinicartItemsFolder(this);
                _wishlistviewform = new DemoSite_01RepositoryFolders.WishlistViewFormFolder(this);
                _kounique1Info = new RepoItemInfo(this, "KoUnique1", ".//div[#'checkout-shipping-method-load']/table//input[@name='ko_unique_1']", "", 30000, null, "f18a001e-155b-4c13-8805-d60af093916f");
                _actionbuttoncontinueprimaryInfo = new RepoItemInfo(this, "ActionButtonContinuePrimary", ".//div[#'shipping-method-buttons-container']/?/?/button", "", 30000, null, "8ae14a52-be96-4d7a-8d4d-bf2d0186c7ca");
                _placeorderInfo = new RepoItemInfo(this, "PlaceOrder", ".//div[#'checkout-payment-method-load']/div/div/div[2]/div[2]/div[4]/?/?/button[@title='Place Order']", "", 30000, null, "5b5596ed-9d03-4fe1-b3bf-ddf36263d7f2");
                _searchInfo = new RepoItemInfo(this, "Search", ".//input[#'search']", "", 30000, null, "723c0e48-c03c-48f7-83f9-31f08b305993");
                _search1Info = new RepoItemInfo(this, "Search1", ".//form[#'search_mini_form']/?/?/button[@title='Search']", "", 30000, null, "445d476f-9df0-4028-9990-fcb57c30c41a");
                _saleInfo = new RepoItemInfo(this, "Sale", ".//div[#'store.menu']/nav//span[@innertext='Sale']", "", 30000, null, "418ab54b-5176-4ab5-a289-412b8487b24d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c7ef2a44-1e29-48dc-9729-4b69cc73a74c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c7ef2a44-1e29-48dc-9729-4b69cc73a74c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The KoUnique1 item.
            /// </summary>
            [RepositoryItem("f18a001e-155b-4c13-8805-d60af093916f")]
            public virtual Ranorex.InputTag KoUnique1
            {
                get
                {
                    return _kounique1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The KoUnique1 item info.
            /// </summary>
            [RepositoryItemInfo("f18a001e-155b-4c13-8805-d60af093916f")]
            public virtual RepoItemInfo KoUnique1Info
            {
                get
                {
                    return _kounique1Info;
                }
            }

            /// <summary>
            /// The ActionButtonContinuePrimary item.
            /// </summary>
            [RepositoryItem("8ae14a52-be96-4d7a-8d4d-bf2d0186c7ca")]
            public virtual Ranorex.ButtonTag ActionButtonContinuePrimary
            {
                get
                {
                    return _actionbuttoncontinueprimaryInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ActionButtonContinuePrimary item info.
            /// </summary>
            [RepositoryItemInfo("8ae14a52-be96-4d7a-8d4d-bf2d0186c7ca")]
            public virtual RepoItemInfo ActionButtonContinuePrimaryInfo
            {
                get
                {
                    return _actionbuttoncontinueprimaryInfo;
                }
            }

            /// <summary>
            /// The PlaceOrder item.
            /// </summary>
            [RepositoryItem("5b5596ed-9d03-4fe1-b3bf-ddf36263d7f2")]
            public virtual Ranorex.ButtonTag PlaceOrder
            {
                get
                {
                    return _placeorderInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The PlaceOrder item info.
            /// </summary>
            [RepositoryItemInfo("5b5596ed-9d03-4fe1-b3bf-ddf36263d7f2")]
            public virtual RepoItemInfo PlaceOrderInfo
            {
                get
                {
                    return _placeorderInfo;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("723c0e48-c03c-48f7-83f9-31f08b305993")]
            public virtual Ranorex.InputTag Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("723c0e48-c03c-48f7-83f9-31f08b305993")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The Search1 item.
            /// </summary>
            [RepositoryItem("445d476f-9df0-4028-9990-fcb57c30c41a")]
            public virtual Ranorex.ButtonTag Search1
            {
                get
                {
                    return _search1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Search1 item info.
            /// </summary>
            [RepositoryItemInfo("445d476f-9df0-4028-9990-fcb57c30c41a")]
            public virtual RepoItemInfo Search1Info
            {
                get
                {
                    return _search1Info;
                }
            }

            /// <summary>
            /// The Sale item.
            /// </summary>
            [RepositoryItem("418ab54b-5176-4ab5-a289-412b8487b24d")]
            public virtual Ranorex.SpanTag Sale
            {
                get
                {
                    return _saleInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Sale item info.
            /// </summary>
            [RepositoryItemInfo("418ab54b-5176-4ab5-a289-412b8487b24d")]
            public virtual RepoItemInfo SaleInfo
            {
                get
                {
                    return _saleInfo;
                }
            }

            /// <summary>
            /// The AccountRegistration folder.
            /// </summary>
            [RepositoryFolder("ee38c34a-b46c-4c9e-abd8-02a5682a5fee")]
            public virtual DemoSite_01RepositoryFolders.AccountRegistrationFolder AccountRegistration
            {
                get { return _accountregistration; }
            }

            /// <summary>
            /// The HeaderLinks folder.
            /// </summary>
            [RepositoryFolder("21fe1bb2-b678-4bdf-b4c6-af9670354fcf")]
            public virtual DemoSite_01RepositoryFolders.HeaderLinksFolder HeaderLinks
            {
                get { return _headerlinks; }
            }

            /// <summary>
            /// The SignInForm folder.
            /// </summary>
            [RepositoryFolder("2914b639-65dd-4153-b3aa-23b3e45a2f64")]
            public virtual DemoSite_01RepositoryFolders.SignInFormFolder SignInForm
            {
                get { return _signinform; }
            }

            /// <summary>
            /// The HeaderCart folder.
            /// </summary>
            [RepositoryFolder("4a4e78b3-cf74-4485-b29a-9ba11d7aca4a")]
            public virtual DemoSite_01RepositoryFolders.HeaderCartFolder HeaderCart
            {
                get { return _headercart; }
            }

            /// <summary>
            /// The Maincontent folder.
            /// </summary>
            [RepositoryFolder("24897bf1-0fc7-40e3-9932-e1b4f58ad63b")]
            public virtual DemoSite_01RepositoryFolders.MaincontentFolder Maincontent
            {
                get { return _maincontent; }
            }

            /// <summary>
            /// The UiCornerAllUiMenuUiWidgetUiWidge folder.
            /// </summary>
            [RepositoryFolder("c1110ff0-1ecc-4ba8-b547-bdcaeac17e4c")]
            public virtual DemoSite_01RepositoryFolders.UiCornerAllUiMenuUiWidgetUiWidgeFolder UiCornerAllUiMenuUiWidgetUiWidge
            {
                get { return _uicorneralluimenuuiwidgetuiwidge; }
            }

            /// <summary>
            /// The MinicartItems folder.
            /// </summary>
            [RepositoryFolder("2a9f0f6a-8588-463b-ab51-390cbcc59670")]
            public virtual DemoSite_01RepositoryFolders.MinicartItemsFolder MinicartItems
            {
                get { return _minicartitems; }
            }

            /// <summary>
            /// The WishlistViewForm folder.
            /// </summary>
            [RepositoryFolder("a1ff9f3f-0648-45e7-aab9-7caf57a3b288")]
            public virtual DemoSite_01RepositoryFolders.WishlistViewFormFolder WishlistViewForm
            {
                get { return _wishlistviewform; }
            }
        }

        /// <summary>
        /// The AccountRegistrationFolder folder.
        /// </summary>
        [RepositoryFolder("ee38c34a-b46c-4c9e-abd8-02a5682a5fee")]
        public partial class AccountRegistrationFolder : RepoGenBaseFolder
        {
            RepoItemInfo _createnewcustomeraccountInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _emailaddressInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _passwordconfirmationInfo;
            RepoItemInfo _createanaccount1Info;
            RepoItemInfo _thankyouforregisteringwithmainwebsInfo;

            /// <summary>
            /// Creates a new AccountRegistration  folder.
            /// </summary>
            public AccountRegistrationFolder(RepoGenBaseFolder parentFolder) :
                    base("AccountRegistration", "dom[@domain='magento.softwaretestingboard.com']", parentFolder, 30000, null, false, "ee38c34a-b46c-4c9e-abd8-02a5682a5fee", "")
            {
                _createnewcustomeraccountInfo = new RepoItemInfo(this, "CreateNewCustomerAccount", ".//main[#'maincontent']//span[@innertext>'Create New Customer Accou']", "", 30000, null, "02f96981-307b-44d2-af25-04b76d1f315e");
                _firstnameInfo = new RepoItemInfo(this, "Firstname", ".//input[#'firstname']", "", 30000, null, "34f792a4-2212-470d-995e-4f67067c382c");
                _lastnameInfo = new RepoItemInfo(this, "Lastname", ".//input[#'lastname']", "", 30000, null, "b4cb696c-f8ef-4c0d-82d5-60db174e6014");
                _emailaddressInfo = new RepoItemInfo(this, "EmailAddress", ".//input[#'email_address']", "", 30000, null, "6c77fa76-e8b4-4329-83dd-004ec1929c94");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", "", 30000, null, "fcb07d2d-7ca7-4599-bfc9-cb95bf7a17b1");
                _passwordconfirmationInfo = new RepoItemInfo(this, "PasswordConfirmation", ".//input[#'password-confirmation']", "", 30000, null, "15798b4a-076c-4ebf-b847-3642d5e320aa");
                _createanaccount1Info = new RepoItemInfo(this, "CreateAnAccount1", ".//form[#'form-validate']//button[@title='Create an Account']/span[@innertext='Create an Account']", "", 30000, null, "46e1a07b-9c03-46e7-bfce-63e0145e629b");
                _thankyouforregisteringwithmainwebsInfo = new RepoItemInfo(this, "ThankYouForRegisteringWithMainWebs", ".//main[#'maincontent']/div[1]//div[@innertext>'Thank you for registering']", "", 30000, null, "74ad3d4c-f342-4d28-8b62-c7131646711e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ee38c34a-b46c-4c9e-abd8-02a5682a5fee")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ee38c34a-b46c-4c9e-abd8-02a5682a5fee")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateNewCustomerAccount item.
            /// </summary>
            [RepositoryItem("02f96981-307b-44d2-af25-04b76d1f315e")]
            public virtual Ranorex.SpanTag CreateNewCustomerAccount
            {
                get
                {
                    return _createnewcustomeraccountInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CreateNewCustomerAccount item info.
            /// </summary>
            [RepositoryItemInfo("02f96981-307b-44d2-af25-04b76d1f315e")]
            public virtual RepoItemInfo CreateNewCustomerAccountInfo
            {
                get
                {
                    return _createnewcustomeraccountInfo;
                }
            }

            /// <summary>
            /// The Firstname item.
            /// </summary>
            [RepositoryItem("34f792a4-2212-470d-995e-4f67067c382c")]
            public virtual Ranorex.InputTag Firstname
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Firstname item info.
            /// </summary>
            [RepositoryItemInfo("34f792a4-2212-470d-995e-4f67067c382c")]
            public virtual RepoItemInfo FirstnameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The Lastname item.
            /// </summary>
            [RepositoryItem("b4cb696c-f8ef-4c0d-82d5-60db174e6014")]
            public virtual Ranorex.InputTag Lastname
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Lastname item info.
            /// </summary>
            [RepositoryItemInfo("b4cb696c-f8ef-4c0d-82d5-60db174e6014")]
            public virtual RepoItemInfo LastnameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The EmailAddress item.
            /// </summary>
            [RepositoryItem("6c77fa76-e8b4-4329-83dd-004ec1929c94")]
            public virtual Ranorex.InputTag EmailAddress
            {
                get
                {
                    return _emailaddressInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EmailAddress item info.
            /// </summary>
            [RepositoryItemInfo("6c77fa76-e8b4-4329-83dd-004ec1929c94")]
            public virtual RepoItemInfo EmailAddressInfo
            {
                get
                {
                    return _emailaddressInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("fcb07d2d-7ca7-4599-bfc9-cb95bf7a17b1")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("fcb07d2d-7ca7-4599-bfc9-cb95bf7a17b1")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The PasswordConfirmation item.
            /// </summary>
            [RepositoryItem("15798b4a-076c-4ebf-b847-3642d5e320aa")]
            public virtual Ranorex.InputTag PasswordConfirmation
            {
                get
                {
                    return _passwordconfirmationInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PasswordConfirmation item info.
            /// </summary>
            [RepositoryItemInfo("15798b4a-076c-4ebf-b847-3642d5e320aa")]
            public virtual RepoItemInfo PasswordConfirmationInfo
            {
                get
                {
                    return _passwordconfirmationInfo;
                }
            }

            /// <summary>
            /// The CreateAnAccount1 item.
            /// </summary>
            [RepositoryItem("46e1a07b-9c03-46e7-bfce-63e0145e629b")]
            public virtual Ranorex.SpanTag CreateAnAccount1
            {
                get
                {
                    return _createanaccount1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CreateAnAccount1 item info.
            /// </summary>
            [RepositoryItemInfo("46e1a07b-9c03-46e7-bfce-63e0145e629b")]
            public virtual RepoItemInfo CreateAnAccount1Info
            {
                get
                {
                    return _createanaccount1Info;
                }
            }

            /// <summary>
            /// The ThankYouForRegisteringWithMainWebs item.
            /// </summary>
            [RepositoryItem("74ad3d4c-f342-4d28-8b62-c7131646711e")]
            public virtual Ranorex.DivTag ThankYouForRegisteringWithMainWebs
            {
                get
                {
                    return _thankyouforregisteringwithmainwebsInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ThankYouForRegisteringWithMainWebs item info.
            /// </summary>
            [RepositoryItemInfo("74ad3d4c-f342-4d28-8b62-c7131646711e")]
            public virtual RepoItemInfo ThankYouForRegisteringWithMainWebsInfo
            {
                get
                {
                    return _thankyouforregisteringwithmainwebsInfo;
                }
            }
        }

        /// <summary>
        /// The HeaderLinksFolder folder.
        /// </summary>
        [RepositoryFolder("21fe1bb2-b678-4bdf-b4c6-af9670354fcf")]
        public partial class HeaderLinksFolder : RepoGenBaseFolder
        {
            RepoItemInfo _actionswitchInfo;
            RepoItemInfo _createanaccountInfo;
            RepoItemInfo _atagsignoutInfo;
            RepoItemInfo _atagsigninInfo;

            /// <summary>
            /// Creates a new HeaderLinks  folder.
            /// </summary>
            public HeaderLinksFolder(RepoGenBaseFolder parentFolder) :
                    base("HeaderLinks", "body/div[2]/header/div[1]/div/ul", parentFolder, 30000, null, false, "21fe1bb2-b678-4bdf-b4c6-af9670354fcf", "")
            {
                _actionswitchInfo = new RepoItemInfo(this, "ActionSwitch", ".//button", "", 30000, null, "435864dd-4497-46a5-9208-a5708f4fb07b");
                _createanaccountInfo = new RepoItemInfo(this, "CreateAnAccount", "?/?/a[@innertext='Create an Account']", "", 30000, null, "0b4a331c-7bc6-4c6e-a430-70fa18026c27");
                _atagsignoutInfo = new RepoItemInfo(this, "ATagSignOut", "?/?/div/ul/?/?/a[@innertext='Sign Out ']", "", 30000, null, "ec36ed6a-be2b-4946-b164-86d70e3f1bda");
                _atagsigninInfo = new RepoItemInfo(this, "ATagSignIn", "?/?/a[@innertext='Sign In ']", "", 30000, null, "b6971fa0-18ca-4220-a212-287be55ceda7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("21fe1bb2-b678-4bdf-b4c6-af9670354fcf")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("21fe1bb2-b678-4bdf-b4c6-af9670354fcf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ActionSwitch item.
            /// </summary>
            [RepositoryItem("435864dd-4497-46a5-9208-a5708f4fb07b")]
            public virtual Ranorex.ButtonTag ActionSwitch
            {
                get
                {
                    return _actionswitchInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ActionSwitch item info.
            /// </summary>
            [RepositoryItemInfo("435864dd-4497-46a5-9208-a5708f4fb07b")]
            public virtual RepoItemInfo ActionSwitchInfo
            {
                get
                {
                    return _actionswitchInfo;
                }
            }

            /// <summary>
            /// The CreateAnAccount item.
            /// </summary>
            [RepositoryItem("0b4a331c-7bc6-4c6e-a430-70fa18026c27")]
            public virtual Ranorex.ATag CreateAnAccount
            {
                get
                {
                    return _createanaccountInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CreateAnAccount item info.
            /// </summary>
            [RepositoryItemInfo("0b4a331c-7bc6-4c6e-a430-70fa18026c27")]
            public virtual RepoItemInfo CreateAnAccountInfo
            {
                get
                {
                    return _createanaccountInfo;
                }
            }

            /// <summary>
            /// The ATagSignOut item.
            /// </summary>
            [RepositoryItem("ec36ed6a-be2b-4946-b164-86d70e3f1bda")]
            public virtual Ranorex.ATag ATagSignOut
            {
                get
                {
                    return _atagsignoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagSignOut item info.
            /// </summary>
            [RepositoryItemInfo("ec36ed6a-be2b-4946-b164-86d70e3f1bda")]
            public virtual RepoItemInfo ATagSignOutInfo
            {
                get
                {
                    return _atagsignoutInfo;
                }
            }

            /// <summary>
            /// The ATagSignIn item.
            /// </summary>
            [RepositoryItem("b6971fa0-18ca-4220-a212-287be55ceda7")]
            public virtual Ranorex.ATag ATagSignIn
            {
                get
                {
                    return _atagsigninInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagSignIn item info.
            /// </summary>
            [RepositoryItemInfo("b6971fa0-18ca-4220-a212-287be55ceda7")]
            public virtual RepoItemInfo ATagSignInInfo
            {
                get
                {
                    return _atagsigninInfo;
                }
            }
        }

        /// <summary>
        /// The SignInFormFolder folder.
        /// </summary>
        [RepositoryFolder("2914b639-65dd-4153-b3aa-23b3e45a2f64")]
        public partial class SignInFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _passInfo;
            RepoItemInfo _signinInfo;
            RepoItemInfo _emailInfo;

            /// <summary>
            /// Creates a new SignInForm  folder.
            /// </summary>
            public SignInFormFolder(RepoGenBaseFolder parentFolder) :
                    base("SignInForm", "", parentFolder, 0, null, false, "2914b639-65dd-4153-b3aa-23b3e45a2f64", "")
            {
                _passInfo = new RepoItemInfo(this, "Pass", ".//form[#'login-form']/fieldset/div[3]/?/?/input[@id='pass']", "", 30000, null, "d05582d0-5812-45a2-b915-41ece52cf1e8");
                _signinInfo = new RepoItemInfo(this, "SignIn", ".//form[#'login-form']//button[@id='send2']/span[@innertext='Sign In']", "", 30000, null, "1265a0ff-39b2-4c5c-9d14-e514576c8b74");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", "", 30000, null, "5f45aa82-1145-4f18-b027-36d3cd227061");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2914b639-65dd-4153-b3aa-23b3e45a2f64")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pass item.
            /// </summary>
            [RepositoryItem("d05582d0-5812-45a2-b915-41ece52cf1e8")]
            public virtual Ranorex.InputTag Pass
            {
                get
                {
                    return _passInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Pass item info.
            /// </summary>
            [RepositoryItemInfo("d05582d0-5812-45a2-b915-41ece52cf1e8")]
            public virtual RepoItemInfo PassInfo
            {
                get
                {
                    return _passInfo;
                }
            }

            /// <summary>
            /// The SignIn item.
            /// </summary>
            [RepositoryItem("1265a0ff-39b2-4c5c-9d14-e514576c8b74")]
            public virtual Ranorex.SpanTag SignIn
            {
                get
                {
                    return _signinInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SignIn item info.
            /// </summary>
            [RepositoryItemInfo("1265a0ff-39b2-4c5c-9d14-e514576c8b74")]
            public virtual RepoItemInfo SignInInfo
            {
                get
                {
                    return _signinInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("5f45aa82-1145-4f18-b027-36d3cd227061")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("5f45aa82-1145-4f18-b027-36d3cd227061")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }
        }

        /// <summary>
        /// The HeaderCartFolder folder.
        /// </summary>
        [RepositoryFolder("4a4e78b3-cf74-4485-b29a-9ba11d7aca4a")]
        public partial class HeaderCartFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cartInfo;
            RepoItemInfo _topcartbtncheckoutInfo;

            /// <summary>
            /// Creates a new HeaderCart  folder.
            /// </summary>
            public HeaderCartFolder(RepoGenBaseFolder parentFolder) :
                    base("HeaderCart", "", parentFolder, 0, null, false, "4a4e78b3-cf74-4485-b29a-9ba11d7aca4a", "")
            {
                _cartInfo = new RepoItemInfo(this, "Cart", "body/div[2]/header/div[2]/div[1]/a[@href>'https://magento.softwaret']", "", 30000, null, "0f77d3f2-44fe-4f6f-9688-227c6cb19ee1");
                _topcartbtncheckoutInfo = new RepoItemInfo(this, "TopCartBtnCheckout", ".//button[#'top-cart-btn-checkout']", "", 30000, null, "d3bc8c8a-7395-4666-a6ac-0221e267a822");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4a4e78b3-cf74-4485-b29a-9ba11d7aca4a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Cart item.
            /// </summary>
            [RepositoryItem("0f77d3f2-44fe-4f6f-9688-227c6cb19ee1")]
            public virtual Ranorex.ATag Cart
            {
                get
                {
                    return _cartInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Cart item info.
            /// </summary>
            [RepositoryItemInfo("0f77d3f2-44fe-4f6f-9688-227c6cb19ee1")]
            public virtual RepoItemInfo CartInfo
            {
                get
                {
                    return _cartInfo;
                }
            }

            /// <summary>
            /// The TopCartBtnCheckout item.
            /// </summary>
            [RepositoryItem("d3bc8c8a-7395-4666-a6ac-0221e267a822")]
            public virtual Ranorex.ButtonTag TopCartBtnCheckout
            {
                get
                {
                    return _topcartbtncheckoutInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The TopCartBtnCheckout item info.
            /// </summary>
            [RepositoryItemInfo("d3bc8c8a-7395-4666-a6ac-0221e267a822")]
            public virtual RepoItemInfo TopCartBtnCheckoutInfo
            {
                get
                {
                    return _topcartbtncheckoutInfo;
                }
            }
        }

        /// <summary>
        /// The MaincontentFolder folder.
        /// </summary>
        [RepositoryFolder("24897bf1-0fc7-40e3-9932-e1b4f58ad63b")]
        public partial class MaincontentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _divtagmInfo;
            RepoItemInfo _addtocartInfo;
            RepoItemInfo _atagcircehoodedicefleeceInfo;
            RepoItemInfo _colorswatchoptionInfo;
            RepoItemInfo _hoodiessweatshirtsInfo;
            RepoItemInfo _thankyouforyourpurchaseInfo;
            RepoItemInfo _itemproductproductitemInfo;
            RepoItemInfo _atagdidisportwatchInfo;
            RepoItemInfo _addtowishlistInfo;
            RepoItemInfo _divtagdidisportwatchhasbeenaddedtInfo;
            RepoItemInfo _fitnessequipmentInfo;
            RepoItemInfo _addtowishlist1Info;
            RepoItemInfo _divtagsetofspriteyogastrapshasbeeInfo;
            RepoItemInfo _atagsetofspriteyogastrapsInfo;
            RepoItemInfo _youaresignedoutInfo;

            /// <summary>
            /// Creates a new Maincontent  folder.
            /// </summary>
            public MaincontentFolder(RepoGenBaseFolder parentFolder) :
                    base("Maincontent", ".//main[#'maincontent']", parentFolder, 30000, null, false, "24897bf1-0fc7-40e3-9932-e1b4f58ad63b", "")
            {
                _divtagmInfo = new RepoItemInfo(this, "DivTagM", "div[3]/div[1]/div[3]/ol/li[1]//div[@innertext='M']", "", 30000, null, "4cb662bf-8192-411d-9518-fca4b513a208");
                _addtocartInfo = new RepoItemInfo(this, "AddToCart", "div[3]/div[1]/div[3]/ol/li[1]//form[@action='https://magento.softwaretestingboard.com/checkout/cart/add/uenc/aHR0cHM6Ly9tYWdlbnRvLnNvZnR3YXJldGVzdGluZ2JvYXJkLmNvbS93b21lbi90b3BzLXdvbWVuL2hvb2RpZXMtYW5kLXN3ZWF0c2hpcnRzLXdvbWVuLmh0bWw%2C/product/1210/']/button[@title='Add to Cart']/span[@innertext='Add to Cart']", "", 30000, null, "e30b2414-aca6-45fe-9367-cabf0c305006");
                _atagcircehoodedicefleeceInfo = new RepoItemInfo(this, "ATagCirceHoodedIceFleece", "div[3]/div[1]/div[3]/ol/li[1]//a[@innertext='Circe Hooded Ice Fleece ']", "", 30000, null, "f9840e1b-03c5-4201-ad0b-d795f3ba56a5");
                _colorswatchoptionInfo = new RepoItemInfo(this, "ColorSwatchOption", "div[3]/div[1]/div[3]/ol/li[1]/div/div/div[2]/div[2]/div/div[2]", "", 30000, null, "2017286b-f486-4f7f-8ffc-a7dcfeab2bc2");
                _hoodiessweatshirtsInfo = new RepoItemInfo(this, "HoodiesSweatshirts", "div[4]/div[2]/div[2]/div/ul[1]/?/?/a[@innertext='Hoodies & Sweatshirts']", "", 30000, null, "4b5b7ebc-27ea-4a1c-aa49-7a57e7afcf5d");
                _thankyouforyourpurchaseInfo = new RepoItemInfo(this, "ThankYouForYourPurchase", ".//span[@innertext>'Thank you for your purcha']", "", 30000, null, "dee30614-8ec3-4ded-a5f0-a2fc3332356f");
                _itemproductproductitemInfo = new RepoItemInfo(this, "ItemProductProductItem", "div[3]/div[1]/div[2]/?/?/ol/li[5]", "", 30000, null, "cf11f3ec-b663-4fe8-9ca4-b00964058341");
                _atagdidisportwatchInfo = new RepoItemInfo(this, "ATagDidiSportWatch", "div[3]/div[1]/div[2]/?/?/ol/li[5]//a[@innertext='Didi Sport Watch ']", "", 30000, null, "b3e23999-0085-4c82-8026-11d012899821");
                _addtowishlistInfo = new RepoItemInfo(this, "AddToWishList", "div[2]/div/div[1]/div[5]//span[@innertext='Add to Wish List']", "", 30000, null, "232e8f8e-3ee6-4742-b36b-ebc169045e99");
                _divtagdidisportwatchhasbeenaddedtInfo = new RepoItemInfo(this, "DivTagDidiSportWatchHasBeenAddedT", "div[1]//div[@innertext>'Didi Sport Watch has been']", "", 30000, null, "9e788426-ce0d-4480-a052-ac73694649c4");
                _fitnessequipmentInfo = new RepoItemInfo(this, "FitnessEquipment", "div[4]/div[2]/div/div/ul[3]/?/?/a[@innertext='Fitness Equipment']", "", 30000, null, "13cabf8d-dc71-459f-926c-d1efb404a3aa");
                _addtowishlist1Info = new RepoItemInfo(this, "AddToWishList1", "div[3]/div[1]/div[3]/ol/li[2]//a[@title='Add to Wish List']", "", 30000, null, "707b052c-41df-45dd-ac52-8cce68c1430d");
                _divtagsetofspriteyogastrapshasbeeInfo = new RepoItemInfo(this, "DivTagSetOfSpriteYogaStrapsHasBee", "div[1]//div[@innertext>'Set of Sprite Yoga Straps']", "", 30000, null, "504aa3b2-c3ec-455a-a09c-972c47622719");
                _atagsetofspriteyogastrapsInfo = new RepoItemInfo(this, "ATagSetOfSpriteYogaStraps", "div[3]/div[1]/div[3]/ol/li[2]//a[@innertext>'Set of Sprite Yoga Straps']", "", 30000, null, "6b030cb5-0d9a-465a-ba60-a5d048cf10c2");
                _youaresignedoutInfo = new RepoItemInfo(this, "YouAreSignedOut", ".//span", "", 30000, null, "717e703a-e53b-4091-a6d1-1203c34bebb7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("24897bf1-0fc7-40e3-9932-e1b4f58ad63b")]
            public virtual Ranorex.MainTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MainTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("24897bf1-0fc7-40e3-9932-e1b4f58ad63b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DivTagM item.
            /// </summary>
            [RepositoryItem("4cb662bf-8192-411d-9518-fca4b513a208")]
            public virtual Ranorex.DivTag DivTagM
            {
                get
                {
                    return _divtagmInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagM item info.
            /// </summary>
            [RepositoryItemInfo("4cb662bf-8192-411d-9518-fca4b513a208")]
            public virtual RepoItemInfo DivTagMInfo
            {
                get
                {
                    return _divtagmInfo;
                }
            }

            /// <summary>
            /// The AddToCart item.
            /// </summary>
            [RepositoryItem("e30b2414-aca6-45fe-9367-cabf0c305006")]
            public virtual Ranorex.SpanTag AddToCart
            {
                get
                {
                    return _addtocartInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddToCart item info.
            /// </summary>
            [RepositoryItemInfo("e30b2414-aca6-45fe-9367-cabf0c305006")]
            public virtual RepoItemInfo AddToCartInfo
            {
                get
                {
                    return _addtocartInfo;
                }
            }

            /// <summary>
            /// The ATagCirceHoodedIceFleece item.
            /// </summary>
            [RepositoryItem("f9840e1b-03c5-4201-ad0b-d795f3ba56a5")]
            public virtual Ranorex.ATag ATagCirceHoodedIceFleece
            {
                get
                {
                    return _atagcircehoodedicefleeceInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagCirceHoodedIceFleece item info.
            /// </summary>
            [RepositoryItemInfo("f9840e1b-03c5-4201-ad0b-d795f3ba56a5")]
            public virtual RepoItemInfo ATagCirceHoodedIceFleeceInfo
            {
                get
                {
                    return _atagcircehoodedicefleeceInfo;
                }
            }

            /// <summary>
            /// The ColorSwatchOption item.
            /// </summary>
            [RepositoryItem("2017286b-f486-4f7f-8ffc-a7dcfeab2bc2")]
            public virtual Ranorex.DivTag ColorSwatchOption
            {
                get
                {
                    return _colorswatchoptionInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ColorSwatchOption item info.
            /// </summary>
            [RepositoryItemInfo("2017286b-f486-4f7f-8ffc-a7dcfeab2bc2")]
            public virtual RepoItemInfo ColorSwatchOptionInfo
            {
                get
                {
                    return _colorswatchoptionInfo;
                }
            }

            /// <summary>
            /// The HoodiesSweatshirts item.
            /// </summary>
            [RepositoryItem("4b5b7ebc-27ea-4a1c-aa49-7a57e7afcf5d")]
            public virtual Ranorex.ATag HoodiesSweatshirts
            {
                get
                {
                    return _hoodiessweatshirtsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HoodiesSweatshirts item info.
            /// </summary>
            [RepositoryItemInfo("4b5b7ebc-27ea-4a1c-aa49-7a57e7afcf5d")]
            public virtual RepoItemInfo HoodiesSweatshirtsInfo
            {
                get
                {
                    return _hoodiessweatshirtsInfo;
                }
            }

            /// <summary>
            /// The ThankYouForYourPurchase item.
            /// </summary>
            [RepositoryItem("dee30614-8ec3-4ded-a5f0-a2fc3332356f")]
            public virtual Ranorex.SpanTag ThankYouForYourPurchase
            {
                get
                {
                    return _thankyouforyourpurchaseInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ThankYouForYourPurchase item info.
            /// </summary>
            [RepositoryItemInfo("dee30614-8ec3-4ded-a5f0-a2fc3332356f")]
            public virtual RepoItemInfo ThankYouForYourPurchaseInfo
            {
                get
                {
                    return _thankyouforyourpurchaseInfo;
                }
            }

            /// <summary>
            /// The ItemProductProductItem item.
            /// </summary>
            [RepositoryItem("cf11f3ec-b663-4fe8-9ca4-b00964058341")]
            public virtual Ranorex.LiTag ItemProductProductItem
            {
                get
                {
                    return _itemproductproductitemInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The ItemProductProductItem item info.
            /// </summary>
            [RepositoryItemInfo("cf11f3ec-b663-4fe8-9ca4-b00964058341")]
            public virtual RepoItemInfo ItemProductProductItemInfo
            {
                get
                {
                    return _itemproductproductitemInfo;
                }
            }

            /// <summary>
            /// The ATagDidiSportWatch item.
            /// </summary>
            [RepositoryItem("b3e23999-0085-4c82-8026-11d012899821")]
            public virtual Ranorex.ATag ATagDidiSportWatch
            {
                get
                {
                    return _atagdidisportwatchInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagDidiSportWatch item info.
            /// </summary>
            [RepositoryItemInfo("b3e23999-0085-4c82-8026-11d012899821")]
            public virtual RepoItemInfo ATagDidiSportWatchInfo
            {
                get
                {
                    return _atagdidisportwatchInfo;
                }
            }

            /// <summary>
            /// The AddToWishList item.
            /// </summary>
            [RepositoryItem("232e8f8e-3ee6-4742-b36b-ebc169045e99")]
            public virtual Ranorex.SpanTag AddToWishList
            {
                get
                {
                    return _addtowishlistInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddToWishList item info.
            /// </summary>
            [RepositoryItemInfo("232e8f8e-3ee6-4742-b36b-ebc169045e99")]
            public virtual RepoItemInfo AddToWishListInfo
            {
                get
                {
                    return _addtowishlistInfo;
                }
            }

            /// <summary>
            /// The DivTagDidiSportWatchHasBeenAddedT item.
            /// </summary>
            [RepositoryItem("9e788426-ce0d-4480-a052-ac73694649c4")]
            public virtual Ranorex.DivTag DivTagDidiSportWatchHasBeenAddedT
            {
                get
                {
                    return _divtagdidisportwatchhasbeenaddedtInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagDidiSportWatchHasBeenAddedT item info.
            /// </summary>
            [RepositoryItemInfo("9e788426-ce0d-4480-a052-ac73694649c4")]
            public virtual RepoItemInfo DivTagDidiSportWatchHasBeenAddedTInfo
            {
                get
                {
                    return _divtagdidisportwatchhasbeenaddedtInfo;
                }
            }

            /// <summary>
            /// The FitnessEquipment item.
            /// </summary>
            [RepositoryItem("13cabf8d-dc71-459f-926c-d1efb404a3aa")]
            public virtual Ranorex.ATag FitnessEquipment
            {
                get
                {
                    return _fitnessequipmentInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FitnessEquipment item info.
            /// </summary>
            [RepositoryItemInfo("13cabf8d-dc71-459f-926c-d1efb404a3aa")]
            public virtual RepoItemInfo FitnessEquipmentInfo
            {
                get
                {
                    return _fitnessequipmentInfo;
                }
            }

            /// <summary>
            /// The AddToWishList1 item.
            /// </summary>
            [RepositoryItem("707b052c-41df-45dd-ac52-8cce68c1430d")]
            public virtual Ranorex.ATag AddToWishList1
            {
                get
                {
                    return _addtowishlist1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AddToWishList1 item info.
            /// </summary>
            [RepositoryItemInfo("707b052c-41df-45dd-ac52-8cce68c1430d")]
            public virtual RepoItemInfo AddToWishList1Info
            {
                get
                {
                    return _addtowishlist1Info;
                }
            }

            /// <summary>
            /// The DivTagSetOfSpriteYogaStrapsHasBee item.
            /// </summary>
            [RepositoryItem("504aa3b2-c3ec-455a-a09c-972c47622719")]
            public virtual Ranorex.DivTag DivTagSetOfSpriteYogaStrapsHasBee
            {
                get
                {
                    return _divtagsetofspriteyogastrapshasbeeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagSetOfSpriteYogaStrapsHasBee item info.
            /// </summary>
            [RepositoryItemInfo("504aa3b2-c3ec-455a-a09c-972c47622719")]
            public virtual RepoItemInfo DivTagSetOfSpriteYogaStrapsHasBeeInfo
            {
                get
                {
                    return _divtagsetofspriteyogastrapshasbeeInfo;
                }
            }

            /// <summary>
            /// The ATagSetOfSpriteYogaStraps item.
            /// </summary>
            [RepositoryItem("6b030cb5-0d9a-465a-ba60-a5d048cf10c2")]
            public virtual Ranorex.ATag ATagSetOfSpriteYogaStraps
            {
                get
                {
                    return _atagsetofspriteyogastrapsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagSetOfSpriteYogaStraps item info.
            /// </summary>
            [RepositoryItemInfo("6b030cb5-0d9a-465a-ba60-a5d048cf10c2")]
            public virtual RepoItemInfo ATagSetOfSpriteYogaStrapsInfo
            {
                get
                {
                    return _atagsetofspriteyogastrapsInfo;
                }
            }

            /// <summary>
            /// The YouAreSignedOut item.
            /// </summary>
            [RepositoryItem("717e703a-e53b-4091-a6d1-1203c34bebb7")]
            public virtual Ranorex.SpanTag YouAreSignedOut
            {
                get
                {
                    return _youaresignedoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The YouAreSignedOut item info.
            /// </summary>
            [RepositoryItemInfo("717e703a-e53b-4091-a6d1-1203c34bebb7")]
            public virtual RepoItemInfo YouAreSignedOutInfo
            {
                get
                {
                    return _youaresignedoutInfo;
                }
            }
        }

        /// <summary>
        /// The UiCornerAllUiMenuUiWidgetUiWidgeFolder folder.
        /// </summary>
        [RepositoryFolder("c1110ff0-1ecc-4ba8-b547-bdcaeac17e4c")]
        public partial class UiCornerAllUiMenuUiWidgetUiWidgeFolder : RepoGenBaseFolder
        {
            RepoItemInfo _womenInfo;

            /// <summary>
            /// Creates a new UiCornerAllUiMenuUiWidgetUiWidge  folder.
            /// </summary>
            public UiCornerAllUiMenuUiWidgetUiWidgeFolder(RepoGenBaseFolder parentFolder) :
                    base("UiCornerAllUiMenuUiWidgetUiWidge", ".//div[#'store.menu']/nav/ul", parentFolder, 30000, null, false, "c1110ff0-1ecc-4ba8-b547-bdcaeac17e4c", "")
            {
                _womenInfo = new RepoItemInfo(this, "Women", "li[2]/a[@href>'https://magento.softwaret']", "", 30000, null, "b84bca7e-1754-42f5-9317-9c6a7d8a1ea2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c1110ff0-1ecc-4ba8-b547-bdcaeac17e4c")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c1110ff0-1ecc-4ba8-b547-bdcaeac17e4c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Women item.
            /// </summary>
            [RepositoryItem("b84bca7e-1754-42f5-9317-9c6a7d8a1ea2")]
            public virtual Ranorex.ATag Women
            {
                get
                {
                    return _womenInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Women item info.
            /// </summary>
            [RepositoryItemInfo("b84bca7e-1754-42f5-9317-9c6a7d8a1ea2")]
            public virtual RepoItemInfo WomenInfo
            {
                get
                {
                    return _womenInfo;
                }
            }
        }

        /// <summary>
        /// The MinicartItemsFolder folder.
        /// </summary>
        [RepositoryFolder("2a9f0f6a-8588-463b-ab51-390cbcc59670")]
        public partial class MinicartItemsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _viewdetailsInfo;
            RepoItemInfo _greenInfo;
            RepoItemInfo _ddtagmInfo;

            /// <summary>
            /// Creates a new MinicartItems  folder.
            /// </summary>
            public MinicartItemsFolder(RepoGenBaseFolder parentFolder) :
                    base("MinicartItems", ".//div[#'opc-sidebar']/div[1]/div/div[2]/?/?/ol", parentFolder, 30000, null, false, "2a9f0f6a-8588-463b-ab51-390cbcc59670", "")
            {
                _viewdetailsInfo = new RepoItemInfo(this, "ViewDetails", ".//span[@innertext='View Details']", "", 30000, null, "d8eb9902-2cbf-4990-aa8f-73e03be4ae93");
                _greenInfo = new RepoItemInfo(this, "Green", "li/div/div//dd[@innertext='Green']", "", 30000, null, "be2adf17-80c5-483d-9d7f-08e4d62a9d3b");
                _ddtagmInfo = new RepoItemInfo(this, "DdTagM", "li/div/div//dd[@innertext='M']", "", 30000, null, "98e457b8-01b4-4b94-bee8-9b6235b8be2d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2a9f0f6a-8588-463b-ab51-390cbcc59670")]
            public virtual Ranorex.OlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.OlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2a9f0f6a-8588-463b-ab51-390cbcc59670")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ViewDetails item.
            /// </summary>
            [RepositoryItem("d8eb9902-2cbf-4990-aa8f-73e03be4ae93")]
            public virtual Ranorex.SpanTag ViewDetails
            {
                get
                {
                    return _viewdetailsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ViewDetails item info.
            /// </summary>
            [RepositoryItemInfo("d8eb9902-2cbf-4990-aa8f-73e03be4ae93")]
            public virtual RepoItemInfo ViewDetailsInfo
            {
                get
                {
                    return _viewdetailsInfo;
                }
            }

            /// <summary>
            /// The Green item.
            /// </summary>
            [RepositoryItem("be2adf17-80c5-483d-9d7f-08e4d62a9d3b")]
            public virtual Ranorex.DdTag Green
            {
                get
                {
                    return _greenInfo.CreateAdapter<Ranorex.DdTag>(true);
                }
            }

            /// <summary>
            /// The Green item info.
            /// </summary>
            [RepositoryItemInfo("be2adf17-80c5-483d-9d7f-08e4d62a9d3b")]
            public virtual RepoItemInfo GreenInfo
            {
                get
                {
                    return _greenInfo;
                }
            }

            /// <summary>
            /// The DdTagM item.
            /// </summary>
            [RepositoryItem("98e457b8-01b4-4b94-bee8-9b6235b8be2d")]
            public virtual Ranorex.DdTag DdTagM
            {
                get
                {
                    return _ddtagmInfo.CreateAdapter<Ranorex.DdTag>(true);
                }
            }

            /// <summary>
            /// The DdTagM item info.
            /// </summary>
            [RepositoryItemInfo("98e457b8-01b4-4b94-bee8-9b6235b8be2d")]
            public virtual RepoItemInfo DdTagMInfo
            {
                get
                {
                    return _ddtagmInfo;
                }
            }
        }

        /// <summary>
        /// The WishlistViewFormFolder folder.
        /// </summary>
        [RepositoryFolder("a1ff9f3f-0648-45e7-aab9-7caf57a3b288")]
        public partial class WishlistViewFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _removeitemInfo;
            RepoItemInfo _didisportwatchInfo;
            RepoItemInfo _setofspriteyogastraps1Info;
            RepoItemInfo _youhavenoitemsinyourwishlistInfo;
            RepoItemInfo _removeitem1Info;

            /// <summary>
            /// Creates a new WishlistViewForm  folder.
            /// </summary>
            public WishlistViewFormFolder(RepoGenBaseFolder parentFolder) :
                    base("WishlistViewForm", ".//form[#'wishlist-view-form']", parentFolder, 30000, null, false, "a1ff9f3f-0648-45e7-aab9-7caf57a3b288", "")
            {
                _removeitemInfo = new RepoItemInfo(this, "RemoveItem", "?/?/ol/li[1]/div/div[3]/?/?/a[@title='Remove Item']", "", 30000, null, "774756ad-faec-4499-b589-f1ff67a0c69d");
                _didisportwatchInfo = new RepoItemInfo(this, "DidiSportWatch", "?/?/ol//strong/a[@innertext='Didi Sport Watch ']", "", 30000, null, "574a69a5-8cab-4348-8269-4759ec594f1b");
                _setofspriteyogastraps1Info = new RepoItemInfo(this, "SetOfSpriteYogaStraps1", "?/?/ol//strong/a[@innertext>'Set of Sprite Yoga Straps']", "", 30000, null, "774618f5-bc58-433f-9da1-637710b8879a");
                _youhavenoitemsinyourwishlistInfo = new RepoItemInfo(this, "YouHaveNoItemsInYourWishList", "?/?/span[@innertext>'You have no items in your']", "", 30000, null, "ee8b240e-9a9e-479e-a91f-cb232ff0195d");
                _removeitem1Info = new RepoItemInfo(this, "RemoveItem1", "?/?/ol/li/div/div[2]/?/?/a[@title='Remove Item']", "", 30000, null, "cdd68df8-eced-48e6-b1ce-ec0782ef241a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a1ff9f3f-0648-45e7-aab9-7caf57a3b288")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a1ff9f3f-0648-45e7-aab9-7caf57a3b288")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RemoveItem item.
            /// </summary>
            [RepositoryItem("774756ad-faec-4499-b589-f1ff67a0c69d")]
            public virtual Ranorex.ATag RemoveItem
            {
                get
                {
                    return _removeitemInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The RemoveItem item info.
            /// </summary>
            [RepositoryItemInfo("774756ad-faec-4499-b589-f1ff67a0c69d")]
            public virtual RepoItemInfo RemoveItemInfo
            {
                get
                {
                    return _removeitemInfo;
                }
            }

            /// <summary>
            /// The DidiSportWatch item.
            /// </summary>
            [RepositoryItem("574a69a5-8cab-4348-8269-4759ec594f1b")]
            public virtual Ranorex.ATag DidiSportWatch
            {
                get
                {
                    return _didisportwatchInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DidiSportWatch item info.
            /// </summary>
            [RepositoryItemInfo("574a69a5-8cab-4348-8269-4759ec594f1b")]
            public virtual RepoItemInfo DidiSportWatchInfo
            {
                get
                {
                    return _didisportwatchInfo;
                }
            }

            /// <summary>
            /// The SetOfSpriteYogaStraps1 item.
            /// </summary>
            [RepositoryItem("774618f5-bc58-433f-9da1-637710b8879a")]
            public virtual Ranorex.ATag SetOfSpriteYogaStraps1
            {
                get
                {
                    return _setofspriteyogastraps1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SetOfSpriteYogaStraps1 item info.
            /// </summary>
            [RepositoryItemInfo("774618f5-bc58-433f-9da1-637710b8879a")]
            public virtual RepoItemInfo SetOfSpriteYogaStraps1Info
            {
                get
                {
                    return _setofspriteyogastraps1Info;
                }
            }

            /// <summary>
            /// The YouHaveNoItemsInYourWishList item.
            /// </summary>
            [RepositoryItem("ee8b240e-9a9e-479e-a91f-cb232ff0195d")]
            public virtual Ranorex.SpanTag YouHaveNoItemsInYourWishList
            {
                get
                {
                    return _youhavenoitemsinyourwishlistInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The YouHaveNoItemsInYourWishList item info.
            /// </summary>
            [RepositoryItemInfo("ee8b240e-9a9e-479e-a91f-cb232ff0195d")]
            public virtual RepoItemInfo YouHaveNoItemsInYourWishListInfo
            {
                get
                {
                    return _youhavenoitemsinyourwishlistInfo;
                }
            }

            /// <summary>
            /// The RemoveItem1 item.
            /// </summary>
            [RepositoryItem("cdd68df8-eced-48e6-b1ce-ec0782ef241a")]
            public virtual Ranorex.ATag RemoveItem1
            {
                get
                {
                    return _removeitem1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The RemoveItem1 item info.
            /// </summary>
            [RepositoryItemInfo("cdd68df8-eced-48e6-b1ce-ec0782ef241a")]
            public virtual RepoItemInfo RemoveItem1Info
            {
                get
                {
                    return _removeitem1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
