///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoSite_01
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SignIn recording.
    /// </summary>
    [TestModule("0bc1c3bb-6ca5-411b-a38c-a9341e19e95a", ModuleType.Recording, 1)]
    public partial class SignIn : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoSite_01Repository repository.
        /// </summary>
        public static DemoSite_01Repository repo = DemoSite_01Repository.Instance;

        static SignIn instance = new SignIn();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SignIn()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SignIn Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'MagentoTesting.HeaderLinks.ATagSignIn'", repo.MagentoTesting.HeaderLinks.ATagSignInInfo, new ActionTimeout(10000), new RecordItemIndex(0));
            repo.MagentoTesting.HeaderLinks.ATagSignInInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\nSign In ') on item 'MagentoTesting.HeaderLinks.ATagSignIn'.", repo.MagentoTesting.HeaderLinks.ATagSignInInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.MagentoTesting.HeaderLinks.ATagSignInInfo, "InnerText", "\nSign In ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.HeaderLinks.ATagSignIn' at 15;10.", repo.MagentoTesting.HeaderLinks.ATagSignInInfo, new RecordItemIndex(2));
            repo.MagentoTesting.HeaderLinks.ATagSignIn.Click("15;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test.account6@gmail.com' with focus on 'MagentoTesting.SignInForm.Email'.", repo.MagentoTesting.SignInForm.EmailInfo, new RecordItemIndex(3));
            repo.MagentoTesting.SignInForm.Email.PressKeys("test.account6@gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test1234' with focus on 'MagentoTesting.SignInForm.Pass'.", repo.MagentoTesting.SignInForm.PassInfo, new RecordItemIndex(4));
            repo.MagentoTesting.SignInForm.Pass.PressKeys("Test1234");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.SignInForm.SignIn' at 37;14.", repo.MagentoTesting.SignInForm.SignInInfo, new RecordItemIndex(5));
            repo.MagentoTesting.SignInForm.SignIn.Click("37;14");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
