///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoSite_01
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The WishlistFunctionality recording.
    /// </summary>
    [TestModule("05854043-be94-419a-90f4-9390815f2f29", ModuleType.Recording, 1)]
    public partial class WishlistFunctionality : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoSite_01Repository repository.
        /// </summary>
        public static DemoSite_01Repository repo = DemoSite_01Repository.Instance;

        static WishlistFunctionality instance = new WishlistFunctionality();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public WishlistFunctionality()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static WishlistFunctionality Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.Maincontent.AddToWishList' at Center.", repo.MagentoTesting.Maincontent.AddToWishListInfo, new RecordItemIndex(0));
            repo.MagentoTesting.Maincontent.AddToWishList.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\nDidi Sport Watch has been added to your Wish List. Click  to continue shopping.') on item 'MagentoTesting.Maincontent.DivTagDidiSportWatchHasBeenAddedT'.", repo.MagentoTesting.Maincontent.DivTagDidiSportWatchHasBeenAddedTInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.MagentoTesting.Maincontent.DivTagDidiSportWatchHasBeenAddedTInfo, "InnerText", "\nDidi Sport Watch has been added to your Wish List. Click  to continue shopping.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.Sale' at Center.", repo.MagentoTesting.SaleInfo, new RecordItemIndex(2));
            repo.MagentoTesting.Sale.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.Maincontent.FitnessEquipment' at Center.", repo.MagentoTesting.Maincontent.FitnessEquipmentInfo, new RecordItemIndex(3));
            repo.MagentoTesting.Maincontent.FitnessEquipment.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MagentoTesting.Maincontent.ATagSetOfSpriteYogaStraps' at Center.", repo.MagentoTesting.Maincontent.ATagSetOfSpriteYogaStrapsInfo, new RecordItemIndex(4));
            repo.MagentoTesting.Maincontent.ATagSetOfSpriteYogaStraps.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(5));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.Maincontent.AddToWishList1' at Center.", repo.MagentoTesting.Maincontent.AddToWishList1Info, new RecordItemIndex(6));
            repo.MagentoTesting.Maincontent.AddToWishList1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\nSet of Sprite Yoga Straps has been added to your Wish List. Click  to continue shopping.') on item 'MagentoTesting.Maincontent.DivTagSetOfSpriteYogaStrapsHasBee'.", repo.MagentoTesting.Maincontent.DivTagSetOfSpriteYogaStrapsHasBeeInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.MagentoTesting.Maincontent.DivTagSetOfSpriteYogaStrapsHasBeeInfo, "InnerText", "\nSet of Sprite Yoga Straps has been added to your Wish List. Click  to continue shopping.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MagentoTesting.WishlistViewForm.DidiSportWatch' at Center.", repo.MagentoTesting.WishlistViewForm.DidiSportWatchInfo, new RecordItemIndex(8));
            repo.MagentoTesting.WishlistViewForm.DidiSportWatch.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.WishlistViewForm.RemoveItem' at 10;13.", repo.MagentoTesting.WishlistViewForm.RemoveItemInfo, new RecordItemIndex(9));
            repo.MagentoTesting.WishlistViewForm.RemoveItem.Click("10;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\nDidi Sport Watch has been removed from your Wish List.\n') on item 'MagentoTesting.Maincontent.DivTagDidiSportWatchHasBeenAddedT'.", repo.MagentoTesting.Maincontent.DivTagDidiSportWatchHasBeenAddedTInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.MagentoTesting.Maincontent.DivTagDidiSportWatchHasBeenAddedTInfo, "InnerText", "\nDidi Sport Watch has been removed from your Wish List.\n");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MagentoTesting.WishlistViewForm.SetOfSpriteYogaStraps1' at Center.", repo.MagentoTesting.WishlistViewForm.SetOfSpriteYogaStraps1Info, new RecordItemIndex(11));
            repo.MagentoTesting.WishlistViewForm.SetOfSpriteYogaStraps1.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MagentoTesting.WishlistViewForm.RemoveItem1' at 7;15.", repo.MagentoTesting.WishlistViewForm.RemoveItem1Info, new RecordItemIndex(12));
            repo.MagentoTesting.WishlistViewForm.RemoveItem1.Click("7;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='You have no items in your wish list.') on item 'MagentoTesting.WishlistViewForm.YouHaveNoItemsInYourWishList'.", repo.MagentoTesting.WishlistViewForm.YouHaveNoItemsInYourWishListInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.MagentoTesting.WishlistViewForm.YouHaveNoItemsInYourWishListInfo, "InnerText", "You have no items in your wish list.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='\nSet of Sprite Yoga Straps has been removed from your Wish List.\n') on item 'MagentoTesting.Maincontent.DivTagSetOfSpriteYogaStrapsHasBee'.", repo.MagentoTesting.Maincontent.DivTagSetOfSpriteYogaStrapsHasBeeInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.MagentoTesting.Maincontent.DivTagSetOfSpriteYogaStrapsHasBeeInfo, "InnerText", "\nSet of Sprite Yoga Straps has been removed from your Wish List.\n");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
